# Generated by Django 4.2.17 on 2024-12-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id_formula', models.AutoField(primary_key=True, serialize=False)),
                ('clean_formula', models.TextField(max_length=300)),
                ('short_description', models.TextField(blank=True, max_length=200)),
                ('meta_inf', models.TextField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'formula',
                'managed': True,
            },
        ),
    ]
