# Generated by Django 4.2.17 on 2024-12-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formula',
            options={'managed': False},
        ),
    ]
