# Generated by Django 4.2.17 on 2024-12-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_alter_formula_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formula',
            options={'managed': True},
        ),
    ]
